/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ManualEntryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SmsPermissionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TransactionListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ManualEntryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/OnboardingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SmsPermissionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TransactionListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `/screens/ManualEntryScreen${`?${string}` | `#${string}` | ''}` | `/screens/OnboardingScreen${`?${string}` | `#${string}` | ''}` | `/screens/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/screens/SmsPermissionScreen${`?${string}` | `#${string}` | ''}` | `/screens/TransactionListScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ManualEntryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SmsPermissionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TransactionListScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
