name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clean install directory
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Installing global tools..."
          npm install -g eas-cli@latest expo-cli@latest
          echo "Installing expo-dev-client..."
          npx expo install expo-dev-client
        continue-on-error: false

      - name: Display Diagnostic Information
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Expo CLI version:"
          expo --version
          echo "EAS CLI version:"
          eas --version
          echo "Package.json contents:"
          cat package.json
          echo "Node modules list:"
          ls -la node_modules

      - name: Verify Expo Login
        run: |
          echo "Authenticating with Expo..."
          if ! eas whoami; then
            echo "Logging in to Expo..."
            if [ -n "${{ secrets.EXPO_TOKEN }}" ]; then
              echo "${{ secrets.EXPO_TOKEN }}" | eas login --non-interactive
            else
              echo "Error: EXPO_TOKEN secret is not set in the repository"
              exit 1
            fi
          fi

      - name: Update EAS Config
        run: |
          echo "Updating eas.json configuration..."
          cat > eas.json << EOF
          {
            "cli": {
              "version": ">= 3.13.3",
              "requireCommit": false
            },
            "build": {
              "development-simulator": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "gradleCommand": ":app:assembleDebug",
                  "buildType": "apk"
                }
              },
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              },
              "preview": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              }
            }
          }
          EOF

      - name: Build Android app
        run: |
          echo "Starting EAS build..."
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
